fix(indexer): Use "count_indexed_tx_global_orders_in_blocking_task" (#9639)
# Description of change

This caused tests to be flaky, and randomly fail with 
```
called `Result::unwrap()` on an `Err` value: Transport(Http(Stream(hyper_util::client::legacy::Error(SendRequest, hyper::Error(IncompleteMessage)))))
```

the reason seemed to be:

```
thread 'tokio-runtime-worker' (42643488) panicked at crates/iota-indexer/src/read.rs:755:9:
you are calling a blocking DB operation directly on an async thread. Please use IndexerReader::spawn_blocking instead to move the operation to a blocking thread
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## Links to any relevant issues

Be sure to reference any related issues by adding `fixes #(issue)`.

## How the change has been tested

Describe the tests that you ran to verify your changes.

Make sure to provide instructions for the maintainer as well as any
relevant configurations.

- [x] Basic tests (linting, compilation, formatting, unit/integration
tests)
- [ ] Patch-specific tests (correctness, functionality coverage)

### Infrastructure QA (only required for crates that are maintained by
@iotaledger/infrastructure)

- [ ] Synchronization of the indexer from genesis for a network
including migration objects.
- [ ] Restart of indexer synchronization locally without resetting the
database.
- [ ] Restart of indexer synchronization on a production-like database.
- [ ] Deployment of services using Docker.
- [ ] Verification of API backward compatibility.