fix: rust docs example compilation (#7715)
# Description of change

Synchronise the version of `fastcrypto` used by the examples with the
one used by the monorepo to avoid import clashes like

```
error[E0599]: no method named `update` found for struct `HashFunctionWrapper` in the current scope
  --> exchange/derive-address.rs:12:12
   |
12 |     hasher.update(example_public_key);
   |            ^^^^^^ method not found in `HashFunctionWrapper<CoreWrapper<CtVariableCoreWrapper<Blake2bVarCore, UInt<UInt<UInt<UInt<..., ...>, ...>, ...>, ...>>>, 32>`
   |
note: there are multiple different versions of crate `fastcrypto` in the dependency graph
  --> /Users/thibault/.cargo/git/checkouts/fastcrypto-9995504e1c5344d5/69d496c/fastcrypto/src/hash.rs:80:1
   |
80 | pub trait HashFunction<const DIGEST_LENGTH: usize>: Default {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ this is the trait that is needed
...
90 |     fn update<Data: AsRef<[u8]>>(&mut self, data: Data);
   |     ---------------------------------------------------- the method is available for `fastcrypto::hash::HashFunctionWrapper<digest::core_api::wrapper::CoreWrapper<digest::core_api::ct_variable::CtVariableCoreWrapper<blake2::Blake2bVarCore, typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UInt<typenum::uint::UTerm, typenum::bit::B1>, typenum::bit::B0>, typenum::bit::B0>, typenum::bit::B0>, typenum::bit::B0>, typenum::bit::B0>>>, 32>` here
   |
  ::: exchange/derive-address.rs:4:5
   |
4  | use fastcrypto::hash::HashFunction;
   |     ------------------------------ `HashFunction` imported here doesn't correspond to the right version of crate `fastcrypto`
   |
  ::: /Users/thibault/.cargo/git/checkouts/fastcrypto-9995504e1c5344d5/2f502fd/fastcrypto/src/hash.rs:80:1
   |
80 | pub trait HashFunction<const DIGEST_LENGTH: usize>: Default {
   | ----------------------------------------------------------- this is the trait that was imported
```

## How the change has been tested

- [x] Basic tests (linting, compilation, formatting, unit/integration
tests)
- [x] Patch-specific tests (correctness, functionality coverage)
- [ ] I have added tests that prove my fix is effective or that my
feature works
- [x] I have checked that new and existing unit tests pass locally with
my changes